version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"  # 使用环境变量
    env_file:
      - .env  # 加载 .env 文件
    volumes:
      - ./backend:/app/backend

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]